---
title: "Leonardo Volpato's resume"
author: Leonardo Volpato
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: 
      - override.css
      - resume
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================


Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> volpato1@msu.edu
- <i class="fa fa-phone"></i> +1 517-505-8582
- <i class="fa fa-home"></i> 6000 62nd AVE UNIT 343, Johnston, IA - USA
- <i class="fa fa-github"></i> [github.com/volpatoo](https://github.com/volpatoo)
- <i class="fa fa-linkedin"></i> [linkedin.com/LV](https://www.linkedin.com/in/leonardo-volpato/)
- <i class="fa fa-file"></i> [cnpq.com/LV](http://lattes.cnpq.br/1956944342787458)
- <i class="fa fa-id-badge"></i> [orcid.org/LV](https://orcid.org/0000-0003-1119-0615)



Statistical software{#skills1}
--------------------------------------------------------------------------------
R, Python, and GIS tools.


Experienced areas{#skills2}
--------------------------------------------------------------------------------

Statistical and bioinformatics analysis, mixed models, GxE interaction, Genotyping and Phenotyping in Plant Breeding. Machine Learning, CNN and Deep Learning. Field performance of UAS-flights. Remote pilot certificate in FAA-USA.


Research strengths {#skills3}
--------------------------------------------------------------------------------

Full experience with remote sensing analysis, drone imagery use and HTP pipelines, Genomic selection and Multi-trait multi-environment models. Machine learning models.


Main
================================================================================

Leonardo Volpato {#title}
--------------------------------------------------------------------------------
### Precision Phenotyping Postdoctoral Research
Corteva Agriscience - Johnston, IA. <br />
June 2023 to present

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------
### Instituto Federal do Triângulo Mineiro - IFTM

T.E. in Technical Course in Agriculture

Uberlandia, Brazil

2009


### Federal University of Viçosa - UFV

B.S. in Agronomy

Viçosa, Brazil

2014


### Federal University of Viçosa - UFV

M.S. in Plant Breeding

Viçosa, Brazil

2016

Thesis: Selection of soybean progeny for grain yield with the use of mixed models


### Federal University of Viçosa - UFV

Ph. D. in Plant Breeding

Viçosa, Brazil

2020

Thesis: High-throughput phenotyping for soybean plant maturity date and wheat plant height using unmanned aerial system


Professional Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------
### Precision Phenotyping Postdoctoral Research Associate

Corteva Agriscience 

Johnston, IA - USA

2023 - present

- Development of precision phenotyping pipelines.
- Remote sensing and proximal sensor development pipelines.
- Precision phenotyping Data Scientist and scientific reports.

### Postdoctoral Research Associate

Michigan State University - MSU

East Lansing, MI - USA

2021 - 2023

- Remote sensing pipelines at dry bean breeding program.
- GxE interactions data analysis.
- Precision phenotyping using ML approaches.  

### Visiting Research Scholar

University Of Minnesota - UMN

Minneapolis, MN - USA

2019 - 2020

- Applied remote sensing approaches in the soybean variety development pipeline.
- Conducted field data analyses using drone imagery.
- Worked collaboratively with other graduate students and technicians.
- Pipeline implemented in R to estimate plant maturity date using HTP/UAS methods


### Visiting Student

International Maize and Wheat Improvement Center - CIMMYT

Mexico City, Mexico

2018 - 2019

- Supported the entire remote sensing components of wheat and maize plant breeding trials.
- Performed drone imagery and software analyses.
- Conducted missions and collected data for HTP using Unmanned Aerial System (UAS).
- Pipeline developed for measuring agronomic trait such as plant height, biomass, lodging and biologic stress using UAS.


### Intern

Federal University of Viçosa - UFV

Viçosa, Brazil

2010 - 2014

::: concise
- Resistance of Spodoptera frugiperda (Lepidoptera: Noctuidae) to proteins from
*Bacillus thuringiensis* 
- Evaluation of tropical maize (*Zea mays* L.) lines fornitrogen use efficiency
- Selection within andbetween families of ornamental pepper (*Capsicum* spp.)
:::

Professional/Academic Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### AgroPlan-UFV - Junior Enterprise Agronomy

Federal University of Viçosa - UFV

Viçosa, Brazil

2011 - 2012


### Teaching assistant in Agriculture Entomology

Federal University of Viçosa - UFV

Viçosa, Brazil

2013 - 2014

### Regulation of seeds and seedlings, Intern 

Federal Agriculture, Livestock and Supply - MAPA

Viçosa, Brazil

2014


### Academic group coordinator 

GenMelhor-UFV - Study Group of Genetics and Breeding

Viçosa, Brazil

2015 2017

### Remote assistance phenotyping

Celeiro Sementes - Pipeline developed to implement phenotyping approaches in the soybean breeding program 

Piaui, Brazil

2021 - 2022


Selected Publications {data-icon=file}
--------------------------------------------------------------------------------

### Selection of inbred soybean progeny: an approach with population effect.

**Volpato, L.**; Simiqueli, G.F.; Alves, R.S.; Rocha, J. R. A. S. C.; Del Conte, M. V.; Resende, M. D. V.; Carneiro, P. C. S.; Silva, F. L. Plant Breeding, v. 138, p. i-iv, 451-672.

N/A

2018 


### A. Multi-trait multi-environment models in the genetic selection of segregating soybean progeny.

**Volpato, L**; Alves, R.S.; Teodoro, P.E.; Resende, V. M. D.; Nascimento, M.; Nascimento, A. C. C.; Ludke, W.H.; Lopes, S. F. PLoS One, v. 14, p. e0215315.

N/A

2019 


### SNP markers associated with soybean partial resistance to Phytophthora sojae.

Ludke, W. H.; Schuster, I.; Nora, T. D.; Oliveira, A. B.; Soares, B. A.; **Volpato, L.**; Silva, F. L. Crop Breeding and Applied Biotechnology, v. 19, p. 31-39

N/A

2019 


### Inference of population effect and progeny selection via a multi-trait index in soybean breeding.

**Volpato, L.**; Rocha, J. R. A. S. C.; Alves, R. S.; Ludke, W. H.; Oliveira, A. B.; Silva, F. L. Acta Scientiarum. Agronomy, v. 43, p. 10.4025/actasci.

N/A

2020 


### High Throughput Field Phenotyping for Plant Height Using UAV-Based RGB Imagery in Wheat Breeding Lines: Feasibility and Validation.

**Volpato, L.**; Pinto, F.; González-Pérez, L. ; Thompson, I. G. ; Borem, A.; Reynolds, M.; Gérard, B.; Molero, G.; Rodrigues, F. A. Frontiers in Plant Science, v. 12, p. 591587.

N/A

2021 


### High Throughput Field Phenotyping for Plant Height Using UAV-Based RGB Imagery in Wheat Breeding Lines: Feasibility and Validation.

**Volpato, L.**; Dobbels. A.; Borem, A,; Lorenz, A. J. The Plant Phenome J.,10.1002/ppj2.20018.

N/A

2021 


### Genomic selection with rapid cycling: Current insights and future prospects.

**Volpato, L.**; Bernardeli, A.; Gomez, F. Crop Breeding and Applied Biotechnology. 21(S): e394721S14.

N/A

2021 


### A Retrospective Analysis of Historical Data of Multi-Environment Trials for Dry Bean (*Phaseolus vulgaris* L.) in Michigan.

**Volpato, L.**; Gomez, F.; Wright E. Crop Science. 10.1002/csc2.21184.

N/A

2023 


### Drone-Based Digital Phenotyping to Evaluating Relative Maturity, Stand Count, and Plant Height in Dry Beans (*Phaseolus vulgaris* L.) .

**Volpato, L.**; Wright, E.; Gomez, F. In press. Plant Phenomics.Preprint at: https://doi.org/10.21203/rs.3.rs-3160633/v1

N/A

2024 



Selected Award {data-icon=trophy}
--------------------------------------------------------------------------------

### National Association of Plant Breeding (NAPB) early career award - Ames, Iowa.

NAPB Graduate Student Poster Competition titled *“Estimation of stand count in dry beans using high resolution imagery: feasibility and validation”*.

N/A

2022


Language {data-icon=globe}
--------------------------------------------------------------------------------

### Portuguese

Native

N/A

N/A 

### English

Fluent

N/A

N/A 
 
### Spanish

Working knowledge

N/A

N/A 
